#!/bin/bash -l
###############################################################################
# This script is the command that is executed every run.
# Check the examples in examples/
#
# This script is run in the execution directory (execDir, --exec-dir).
#
# PARAMETERS:
# $1 is the candidate configuration number
# $2 is the instance ID
# $3 is the seed
# $4 is the instance name
# The rest ($* after `shift 4') are parameters to the run
#
# RETURN VALUE:
# This script should print one numerical value: the cost that must be minimized.
# Exit with 0 if no error, with 1 in case of error
###############################################################################
error() {
    echo "`TZ=UTC date`: $0: error: $@"
    exit 1
}

# This parses the arguments given by irace. Do not touch it!
CONFIG_ID=$1
INSTANCE_ID=$2
SEED=$3
INSTANCE=$4
shift 4 || error "Not enough parameters"
CONFIG_PARAMS=$*
# End of parsing

EXE=/projappl/project_2012477/implementation/adm-emo/adm_emo/rvea_learning.py

EXE_PARAMS="--seed ${SEED} ${INSTANCE} ${CONFIG_PARAMS}"

# If the program just prints a number, we can use 'exec' to avoid
# creating another process, but there can be no other commands after exec.
exec /projappl/project_2012477/implementation/.venv/bin/python $EXE ${EXE_PARAMS}
exit 1